version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9092:9092"
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.0.0
    volumes:
    - ./filebeat/files:/tmp/logs
    - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
    environment:
      XPACK_MONITORING_ENABLED: "false"
    volumes:
    - ./logstash:/usr/share/logstash/pipeline